CREATE TABLE sessoes (
  id VARCHAR(128) NOT NULL PRIMARY KEY,
  dados JSON NOT NULL,
  expira_em DATETIME NOT NULL,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_sessoes_expira_em (expira_em)
) ENGINE=InnoDB;
